// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS26wmS0EWu43WFXQuM99YCcSWUklMgVg',
    appId: '1:436599040197:web:ebf5f669a71b4a3675a8ac',
    messagingSenderId: '436599040197',
    projectId: 'iot-irrigation-d58cc',
    authDomain: 'iot-irrigation-d58cc.firebaseapp.com',
    storageBucket: 'iot-irrigation-d58cc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUbuyFbhTzPYFV8iib1VS0fQMK7Y0LX04',
    appId: '1:436599040197:android:71c41abc15ffe91475a8ac',
    messagingSenderId: '436599040197',
    projectId: 'iot-irrigation-d58cc',
    storageBucket: 'iot-irrigation-d58cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkFBHCHnq44e1epcGzCUpe-0t-ERWcAf0',
    appId: '1:436599040197:ios:01cdd91de9d71d9c75a8ac',
    messagingSenderId: '436599040197',
    projectId: 'iot-irrigation-d58cc',
    storageBucket: 'iot-irrigation-d58cc.appspot.com',
    iosBundleId: 'com.example.iotAlpha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkFBHCHnq44e1epcGzCUpe-0t-ERWcAf0',
    appId: '1:436599040197:ios:35dde9d53942c6dd75a8ac',
    messagingSenderId: '436599040197',
    projectId: 'iot-irrigation-d58cc',
    storageBucket: 'iot-irrigation-d58cc.appspot.com',
    iosBundleId: 'com.example.iotAlpha.RunnerTests',
  );
}
